### ISSUE TITLE
The example Create Task and Assignment fails

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-box#11]
In the entry-point POST /api/box/3/task/addassignment the Parent Folder is null, and the service throw an exception.

When we save the task the file injected in the object is a reduced version of the file type. 

To keep the service simple we should have only one version of Type File.

**Comment by josecollazzi** [comment]
@jonjomckay could you please review

**Comment by jonjomckay** [comment]
LGTM :nail_care:
