### ISSUE TITLE
Not descriptive errors when save not supported types.

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-box#13]
There are some types that can not be saved using box service:

Currently "Save" is supported for "Folder", "Task" and Metadata objects.

We should show a more descriptive error message when someone try to save these types, also we should add in the documentation which are the types that can be saved and loaded.

**Comment by josecollazzi** [comment]
@jonjomckay could you please code review?

**Comment by jonjomckay** [comment]
@josecollazzi just left you a lil comment :+1:

**Comment by josecollazzi** [comment]
@jonjomckay I have made the changes, could you please code review?

**Comment by jonjomckay** [comment]
LGTM :dancer:
