### ISSUE TITLE
Filter By Groups

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-box#17]
We need to improve box-service as Identity to be able to work with other services.
Functionality to allow access to flow to users from only some groups and restrict the access to the others users even if they are from the same Enterprise. 

The test, examples and docs also need to be updated.

**Comment by josecollazzi** [comment]
The service allow restrict access by group, but box doesn't show the group id in any place, and also the list of group is deactivate in the service, so even if the code is there is not active at the moment.

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review?

**Comment by jonjomckay** [comment]
@josecollazzi yeah that's fine, LGTM :yin_yang:
