### ISSUE TITLE
We need to add some examples.

### ISSUE THREAD

**Issue by ghost** [manywho/service-box#3]
We need to add flow examples to help to understand how this service works and can also run in QA to check that specific functionality is working.

The examples should include the Box Service, can include also ManyWho Identity Service if need it but not others, to keep the flow easy to maintain.

Blank out any credentials in configuration values.

The default value for the services should be staging.

The README.md in the Examples repository should have all the information need it to run the flows.

**Comment by josecollazzi** [comment]
@jonjomckay could you please code review?

**Comment by jonjomckay** [comment]
LGTM :100:
