### ISSUE TITLE
Support for limit and offset when loading files

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-box#31]
Support for limit and offset when loading files using a filter.

**Comment by josecollazzi** [comment]
@jonjomckay could you please review?

**Comment by jonjomckay** [comment]
@josecollazzi I think this could be more genericized (i.e. it's not just files that can have an offset and limit). This is how the SDK 2 does it: https://github.com/manywho/sdk-java/blob/develop/sdk-services/src/main/java/com/manywho/sdk/services/database/DatabaseLoadService.java#L26

**Comment by josecollazzi** [comment]
@jonjomckay Ok, it looks better that way, but it doesn't make sense to re-implement that functionality. I have added an issue to update this service to SDK 2.0 and a comment about this specific functionality. I would like to add this specific functionality to files at this point, and just switch to SDK 2 the full-service latter.
Could you please pass the review if you agree with the plan?

**Comment by jonjomckay** [comment]
@josecollazzi cool OK, sounds good to me :)
