### ISSUE TITLE
Launching a flow from box produce an error

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-box#40]
Logs errors:
````
Caused by: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: 1.2.840.113549.1.5.13 not available: no such algorithm: PBKDF2with8BIT for provider BC
````

**Comment by josecollazzi** [comment]
The issue was fixed downgrading the box sdk to 2.25

**Comment by josecollazzi** [comment]
@jonjomckay could you please review the code? 
to review all the changes from before starting with this ticket
git diff 955a46b51e8239a2691a5ae1d417e0abd3f7a876

sorry for the messy comments

**Comment by jonjomckay** [comment]
@josecollazzi LGTM :+1:
