### ISSUE TITLE
Use a save for Create Task and Folder

### ISSUE THREAD

**Issue by ghost** [manywho/service-box#6]
change "Folder: Create" action to a "Save" object Folder
change "Task: Create" action to "Save" object Task

These changes are for keep a consistence in the way we define operations (these are crud actions)

**Comment by ghost** [comment]
@jonjomckay  could you please review?

**Comment by jonjo-manywho** [comment]
@jose-manywho I just added a couple of review comments for you to take a look at

**Comment by ghost** [comment]
thanks @jonjomckay I have made the changes, could you please review.

**Comment by jonjo-manywho** [comment]
LGTM :shipit:

**Comment by josecollazzi** [comment]
@jonjomckay  I have removed two not used classes.
