### ISSUE TITLE
Remove not used classes and refactoring packages

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-box#9]
Some classes can be removed, after the issue #6 
And some packages can be refactored:

The package 

Because requests is generic and all the entities in the requests folder are now request for actions we can rename the package:

com.manywho.services.box.entities.requests -> com.manywho.services.box.entities.actions

And because are not really properties are types we can rename this package:

com.manywho.services.box.property -> com.manywho.services.box.entities.types

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review

**Comment by jonjomckay** [comment]
LGTM :racehorse:
